package com.example.cinema.admin.model;

public enum Country {
    Argentina("Argentina"),
    Armenia("Armenia"),
    Australia("Australia"),
    Austria("Austria"),
    Azerbaijan("Azerbaijan"),
    Belarus("Belarus"),
    Belgium("Belgium"),
    Brazil("Brazil"),
    Bulgaria("Bulgaria"),
    Canada("Canada"),
    Chile("Chile"),
    China("China"),
    Colombia("Colombia"),
    CostaRica("Costa-Rica"),
    Croatia("Croatia"),
    CzechRepublic("Czech Republic"),
    Denmark("Denmark"),
    Dominica("Dominica"),
    DominicanRepublic("Dominican Republic"),
    Egypt("Egypt"),
    Estonia("Estonia"),
    Finland("Finland"),
    France("France"),
    Georgia("Georgia"),
    Germany("Germany"),
    Greece("Greece"),
    HongKong("Hong Kong"),
    Hungary("Hungary"),
    Iceland("Iceland"),
    India("India"),
    Indonesia("Indonesia"),
    Iran("Iran"),
    Iraq("Iraq"),
    Ireland("Ireland"),
    Israel("Israel"),
    Italy("Italy"),
    Japan("Japan"),
    Kazakhstan("Kazakhstan"),
    NorthKorea("North Korea"),
    SouthKorea("South Korea"),
    Latvia("Latvia"),
    Lithuania("Lithuania"),
    Madagascar("Madagascar"),
    Malaysia("Malaysia"),
    Maldives("Maldives"),
    Mexico("Mexico"),
    Moldova("Moldova"),
    Mongolia("Mongolia"),
    Montenegro("Montenegro"),
    Nepal("Nepal"),
    Netherlands("Netherlands"),
    NewZealand("New Zealand"),
    Norway("Norway"),
    Pakistan("Pakistan"),
    Paraguay("Paraguay"),
    Peru("Peru"),
    Philippines("Philippines"),
    Poland("Poland"),
    Portugal("Portugal"),
    PuertoRico("PuertoRico"),
    Romania("Romania"),
    Russia("Russia"),
    SaudiArabia("Saudi Arabia"),
    Serbia("Serbia"),
    Singapore("Singapore"),
    Slovakia("Slovakia"),
    Slovenia("Slovenia"),
    SouthAfrica("South Africa"),
    Spain("Spain"),
    SriLanka("SriLanka"),
    Sweden("Sweden"),
    Switzerland("Switzerland"),
    Taiwan("Taiwan"),
    Tajikistan("Tajikistan"),
    Thailand("Thailand"),
    Turkey("Turkey"),
    Ukraine("Ukraine"),
    UAE("UAE"),
    UnitedKingdom("United Kingdom"),
    USA("USA"),
    Uruguay("Uruguay"),
    Uzbekistan("Uzbekistan"),
    Venezuela("Venezuela"),
    Vietnam("Vietnam");

    private final String label;

    Country(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }
}
