<!-- Search bar -->
<div class="search-wrapper">
    <div class="container container--add">
        <form id='search-form' method='get' class="search" action="/navigator">
            <input name="search" type="text" class="search__field" placeholder="Search">
            <input name="sort" type="hidden" value="popularity">
            <button type='submit' class="btn btn-md btn--danger search__button">search a movie</button>
        </form>
    </div>
</div>